package enum

const (
	ERROR_CODE_TEAM_EXISTS  string = "TEAM_EXISTS"
	ERROR_CODE_PR_EXISTS    string = "PR_EXISTS"
	ERROR_CODE_PR_MERGED    string = "PR_MERGED"
	ERROR_CODE_NOT_ASSIGNED string = "NOT_ASSIGNED"
	ERROR_CODE_NO_CANDIDATE string = "NO_CANDIDATE"
	ERROR_CODE_NOT_FOUND    string = "NOT_FOUND"

	PR_STATUS_OPEN   string = "OPEN"
	PR_STATUS_MERGED string = "MERGED"
)
